<?php
require_once __DIR__.'/config/database.php'; require_once __DIR__.'/config/google_sheets.php';
if(!is_admin()){header('Location: dashboard.php');exit;}
$id=(int)($_GET['id']??0);if($id<=0){header('Location: vendeurs.php');exit;}
$error='';$success='';
$getVendor=$pdo->prepare("SELECT id,username,full_name,seller_phone,active,created_at FROM users WHERE id=? AND role='vendeur'");$getVendor->execute([$id]);$vendor=$getVendor->fetch();if(!$vendor){header('Location: vendeurs.php');exit;}

if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='update_vendor'){
  $name=trim($_POST['full_name']??'');$username=trim($_POST['username']??'');$phone=trim($_POST['seller_phone']??'');$pass=$_POST['password']??'';
  if($name===''||$username==='')$error='Le nom et l’identifiant sont obligatoires.';else try{if($pass!==''){if(strlen($pass)<6)throw new RuntimeException('Le nouveau mot de passe doit contenir au moins 6 caractères.');$q=$pdo->prepare("UPDATE users SET full_name=?,username=?,seller_phone=?,password_hash=? WHERE id=? AND role='vendeur'");$q->execute([$name,$username,$phone,password_hash($pass,PASSWORD_DEFAULT),$id]);}else{$q=$pdo->prepare("UPDATE users SET full_name=?,username=?,seller_phone=? WHERE id=? AND role='vendeur'");$q->execute([$name,$username,$phone,$id]);}$success='Vendeur modifié avec succès.';}catch(RuntimeException $e){$error=$e->getMessage();}catch(PDOException $e){$error='Impossible de modifier : cet identifiant est peut-être déjà utilisé.';}
 }
 if($action==='delete_vendor'){
  try{$n=(int)$pdo->query('SELECT COUNT(*) FROM subscriptions WHERE seller_id='.(int)$id)->fetchColumn();if($n>0)throw new RuntimeException('Impossible d’effacer ce vendeur car il possède des souscriptions. Désactivez-le à la place.');$n2=(int)$pdo->query('SELECT COUNT(*) FROM sim_stock_affectations WHERE seller_id='.(int)$id)->fetchColumn();if($n2>0)throw new RuntimeException('Impossible d’effacer ce vendeur car il possède des affectations de stock.');$pdo->prepare("DELETE FROM users WHERE id=? AND role='vendeur'")->execute([$id]);header('Location: vendeurs.php?deleted=1');exit;}catch(RuntimeException $e){$error=$e->getMessage();}
 }
 if($action==='delete_subscription'){
  $sid=(int)($_POST['subscription_id']??0);try{$pdo->beginTransaction();$q=$pdo->prepare('SELECT stock_allocation_id FROM subscriptions WHERE id=? AND seller_id=? FOR UPDATE');$q->execute([$sid,$id]);$sub=$q->fetch();if(!$sub)throw new RuntimeException('Souscription introuvable.');$pdo->prepare('DELETE FROM subscriptions WHERE id=? AND seller_id=?')->execute([$sid,$id]);if(!empty($sub['stock_allocation_id']))$pdo->prepare('UPDATE sim_stock_affectations SET quantity_remaining=LEAST(quantity_initial,quantity_remaining+1) WHERE id=?')->execute([(int)$sub['stock_allocation_id']]);$pdo->commit();$success='Souscription effacée et 1 SIM rendue à l’affectation du vendeur.';if(google_sheets_url($pdo)!=='')sync_google_sheets($pdo);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Impossible d’effacer la souscription.';}
 }
 if($action==='edit_subscription'){
  $sid=(int)($_POST['subscription_id']??0);$sim=normalize_sim_number((string)($_POST['sim_number']??''));$dep=trim($_POST['first_deposit_reference']??'');$bun=trim($_POST['first_bundle_reference']??'');$mob=trim($_POST['mobile_money_reference']??'');$notes=trim($_POST['notes']??'');
  $op=detect_operator_from_sim($sim);if($sim===''||$op==='Autre')$error='Numéro invalide ou opérateur impossible à détecter.';else try{$q=$pdo->prepare('SELECT stock_allocation_id,operator FROM subscriptions WHERE id=? AND seller_id=?');$q->execute([$sid,$id]);$sub=$q->fetch();if(!$sub)throw new RuntimeException('Souscription introuvable.');if($op!==$sub['operator'])throw new RuntimeException('Impossible de changer d’opérateur lors de la modification.');$duplicate=find_duplicate_sim($pdo,$sim,$sid);if($duplicate)throw new RuntimeException('⚠️ Ce numéro SIM est déjà souscrit dans le système. Modification annulée.');$q=$pdo->prepare('UPDATE subscriptions SET sim_number=?,first_deposit_reference=?,first_bundle_reference=?,mobile_money_reference=?,notes=? WHERE id=? AND seller_id=?');$q->execute([$sim,$dep,$bun,$mob,$notes,$sid,$id]);$success='Souscription modifiée avec succès.';if(google_sheets_url($pdo)!=='')sync_google_sheets($pdo);}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Impossible de modifier la souscription.';}
 }
}
$getVendor->execute([$id]);$vendor=$getVendor->fetch();
$total=(int)$pdo->query('SELECT COUNT(*) FROM subscriptions WHERE seller_id='.(int)$id)->fetchColumn();$today=(int)$pdo->query('SELECT COUNT(*) FROM subscriptions WHERE seller_id='.(int)$id.' AND subscription_date=CURDATE()')->fetchColumn();
$firstSt=$pdo->prepare('SELECT * FROM subscriptions WHERE seller_id=? ORDER BY subscription_date ASC,id ASC LIMIT 1');$firstSt->execute([$id]);$first=$firstSt->fetch();
$operators=$pdo->query('SELECT operator,COUNT(*) total FROM subscriptions WHERE seller_id='.(int)$id.' GROUP BY operator ORDER BY total DESC,operator')->fetchAll();
$alloc=$pdo->query('SELECT operator,SUM(quantity_initial) assigned,SUM(quantity_remaining) remaining FROM sim_stock_affectations WHERE seller_id='.(int)$id.' GROUP BY operator')->fetchAll();
$subscriptions=$pdo->query('SELECT * FROM subscriptions WHERE seller_id='.(int)$id.' ORDER BY subscription_date DESC,id DESC LIMIT 50')->fetchAll();
include __DIR__.'/includes/header.php';?>
<div class="page-head"><div><h1>Fiche vendeur</h1><p class="muted">Gestion complète du compte, des affectations et des souscriptions.</p></div><div class="actions"><a class="btn secondary" href="vendeurs.php">← Vendeurs</a><form method="post" style="display:inline" onsubmit="return confirm('Effacer définitivement ce vendeur ?')"><input type="hidden" name="action" value="delete_vendor"><button class="btn danger">Effacer le vendeur</button></form></div></div>
<?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?>
<div class="cards"><div class="card"><div class="muted">Souscriptions</div><div class="stat"><?=$total?></div></div><div class="card"><div class="muted">Aujourd’hui</div><div class="stat"><?=$today?></div></div><div class="card"><div class="muted">Statut</div><div class="stat" style="font-size:20px"><?=$vendor['active']?'Actif':'Inactif'?></div></div></div>
<div class="grid2"><div class="form-card"><h3>Modifier le vendeur</h3><form method="post"><input type="hidden" name="action" value="update_vendor"><label>Nom complet *<input name="full_name" value="<?=e($vendor['full_name'])?>" required></label><label>Téléphone vendeur<input name="seller_phone" value="<?=e($vendor['seller_phone'])?>"></label><label>Identifiant *<input name="username" value="<?=e($vendor['username'])?>" required></label><label>Nouveau mot de passe <span class="muted">(facultatif)</span><input type="password" name="password" minlength="6"></label><button class="btn primary">💾 Modifier le vendeur</button></form></div>
<div class="card"><h3>SIM affectées au vendeur</h3><?php if($alloc):?><div class="operator-list"><?php foreach($alloc as $a):?><div><span><?=e($a['operator'])?></span><strong><?=e((string)$a['remaining'])?> / <?=e((string)$a['assigned'])?></strong></div><?php endforeach;?></div><?php else:?><p class="muted">Aucune SIM affectée.</p><?php endif;?><div class="actions" style="margin-top:16px"><a class="btn primary" href="stock_affecter.php">＋ Affecter des SIM</a></div></div></div>
<div class="card" style="margin-top:20px"><h3>Première souscription</h3><?php if($first):?><div class="info-list"><div><span>SIM</span><strong><?=e($first['sim_number'])?></strong></div><div><span>Opérateur</span><strong><?=e($first['operator'])?></strong></div><div><span>1er dépôt</span><strong><?=e($first['first_deposit_reference']?:'—')?></strong></div><div><span>1er achat offre</span><strong><?=e($first['first_bundle_reference']?:'—')?></strong></div><div><span>Mobile Money</span><strong><?=e($first['mobile_money_reference']?:'—')?></strong></div></div><?php else:?><p class="empty">Aucune souscription.</p><?php endif;?></div>
<div class="card table-card" style="margin-top:20px"><h3>Historique des souscriptions — modifier / effacer</h3><table class="table"><thead><tr><th>Date</th><th>SIM</th><th>Opérateur</th><th>1er dépôt</th><th>1er forfait</th><th>Mobile Money</th><th>Actions</th></tr></thead><tbody>
<?php foreach($subscriptions as $r):?><tr><td><?=e(date('d/m/Y',strtotime($r['subscription_date'])))?></td><td><?=e($r['sim_number'])?></td><td><span class="badge"><?=e($r['operator'])?></span></td><td><?=e($r['first_deposit_reference']?:'—')?></td><td><?=e($r['first_bundle_reference']?:'—')?></td><td><?=e($r['mobile_money_reference']?:'—')?></td><td><details><summary class="btn secondary small">Modifier</summary><form method="post" style="min-width:280px;margin-top:8px"><input type="hidden" name="action" value="edit_subscription"><input type="hidden" name="subscription_id" value="<?=$r['id']?>"><input name="sim_number" value="<?=e($r['sim_number'])?>" placeholder="SIM" required><input name="first_deposit_reference" value="<?=e($r['first_deposit_reference'])?>" placeholder="1er dépôt"><input name="first_bundle_reference" value="<?=e($r['first_bundle_reference'])?>" placeholder="1er forfait"><input name="mobile_money_reference" value="<?=e($r['mobile_money_reference'])?>" placeholder="Mobile Money"><button class="btn primary small">Enregistrer</button></form></details><form method="post" style="display:inline" onsubmit="return confirm('Effacer cette souscription ?')"><input type="hidden" name="action" value="delete_subscription"><input type="hidden" name="subscription_id" value="<?=$r['id']?>"><button class="btn danger small">Effacer</button></form></td></tr><?php endforeach;?><?php if(!$subscriptions):?><tr><td colspan="7" class="empty">Aucune souscription.</td></tr><?php endif;?></tbody></table></div>
<?php include __DIR__.'/includes/footer.php';?>
